name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_GOOGLE_SCRIPT_URL: ${{ secrets.VITE_GOOGLE_SCRIPT_URL }}
        run: npm run build

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_WEB_SSH_KEY_RAW }}

      - name: Run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DO_WEB_HOST }} '/root/deploy-petwell.sh'

      - name: Deploy files
        run: |
          rsync -avz --delete \
            dist/ \
            root@${{ secrets.DO_WEB_HOST }}:/var/www/petwell/

      - name: Fix permissions
        run: |
          ssh root@${{ secrets.DO_WEB_HOST }} 'chown -R www-data:www-data /var/www/petwell && chmod -R 755 /var/www/petwell'

      - name: Verify deployment
        run: |
          ssh root@${{ secrets.DO_WEB_HOST }} 'ls -la /var/www/petwell'
