name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          VITE_GOOGLE_SCRIPT_URL: ${{ secrets.VITE_GOOGLE_SCRIPT_URL }}
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_WEB_SSH_KEY }}" | tr -d '\n' | base64 -d > ~/.ssh/do_web
          chmod 600 ~/.ssh/do_web
          ssh-keyscan -H ${{ secrets.DO_WEB_HOST }} >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh

      - name: Start SSH Agent
        run: |
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/do_web

      - name: Run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DO_WEB_HOST }} '/root/deploy-petwell.sh'

      - name: Deploy files
        run: |
          rsync -avz --delete \
            dist/ \
            root@${{ secrets.DO_WEB_HOST }}:/var/www/petwell/

      - name: Verify deployment
        run: |
          ssh root@${{ secrets.DO_WEB_HOST }} 'ls -la /var/www/petwell'
